name: build images
on:
    push:
        branches:
            - main
jobs:
    image_build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: setup qemu
              uses: docker/setpup-qemu-action@v3
              
            - name: setup docker build
              uses: docker/setup-buildx-action@v3
            
            - name: Login to dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USER}}
                password: ${{secrets.DOCKER_PWD}}
            
            - name: build and push docker image
              uses: docker/build-push-action@v5
              with:
                contenxt: .
                file: backend/Dockerfile
                push: true
                platforms: linux/and64,linux/arm64
                tags: jasonfywang/goldapmanage:v1.0

